### ISSUE TITLE
Clean install on Windows does not work

### ISSUE THREAD

**Issue by spgennard** [brunopacheco1/coboldoc#18]
```batch

# npm i -g coboldoc
C:\Users\Stephen Gennard\AppData\Roaming\npm\coboldoc -> C:\Users\Stephen Gennard\AppData\Roaming\npm\node_modules\coboldoc\lib\index.js
+ coboldoc@1.2.0
added 26 packages from 63 contributors in 6.889s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.7 -> 6.14.8      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.8   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯


o:\R16
# coboldoc
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\Stephen Gennard\AppData\Roaming\npm\node_modules\coboldoc\node_modules\kleur'
←[90m    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)←[39m
←[90m    at applyExports (internal/modules/cjs/loader.js:492:14)←[39m
←[90m    at resolveExports (internal/modules/cjs/loader.js:541:12)←[39m
←[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)←[39m
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:847:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1016:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:69:18)←[39m
    at Object.<anonymous> (C:\Users\Stephen Gennard\AppData\Roaming\npm\node_modules\←[4mcoboldoc←[24m\lib\controllers\cli.js:7:41)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1121:30)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m
}
```

**Comment by spgennard** [comment]
Fixed by update nodejs, you might want to update the docs.

```text
Now, kleur specifically, will still work for Node >= 6 and Node >= 13.7. Only the early 13.x versions will fail.
```

https://github.com/lukeed/kleur/issues/32
