### ISSUE TITLE
Failed package 

### ISSUE THREAD

**Issue by OlegKunitsyn** [brunopacheco1/coboldoc#4]
The tool works locally but fails after installation as global NPM package:

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '../lib/index.js'
Require stack:
- /usr/local/lib/node_modules/coboldoc/bin/coboldoc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/coboldoc/bin/coboldoc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/coboldoc/bin/coboldoc' ]
```

**Comment by brunopacheco1** [comment]
I believe it should be fixed now, I moved some classes but one path wasn't updated correctly.

**Comment by OlegKunitsyn** [comment]
Please release that fix. Npmjs has only 1.0.0. available.

**Comment by brunopacheco1** [comment]
I did the release as you asked, but it won't do anything, I am still working on the parser. The first published package was just to get the project name, but it is too early to have the first MVP.

**Comment by OlegKunitsyn** [comment]
Thank you!
